#ifndef __BACKEND_OPERATION_DEFINES
#define __BACKEND_OPERATION_DEFINES

/* Result of a process-unregister operation */
#define PROCESS_UNREGISTER_RESULT_SUCCESS		0
#define PROCESS_UNREGISTER_RESULT_HOLDS_LOCKS	1
#define PROCESS_UNREGISTER_RESULT_NON_EXISTENT	2

#endif /* __BACKEND_OPERATION_DEFINES */
